CREATE DATABASE dbMarket2023;

ON
(
NAME = 'Market2023',
FILENAME = 'C:\VENTAS\Market2023.mdf',
SIZE = 15MB,
MAXSIZE = 50MB,
FILEGROWTH = 5MB
)

LOG ON (
NAME = 'Market2023_Data',
FILENAME = 'C:\VENTAS\Market2023.ndf',
SIZE = 30MB,
MAXSIZE = 100MB,
FILEGROWTH = 25%
)
LOG ON (
NAME = 'Market2023_Log',
FILENAME = 'C:\VENTAS\Market2023.ldf',
SIZE = 60MB,
MAXSIZE = 150MB,
FILEGROWTH = 20%
);


CREATE SCHEMA PERSONA;
CREATE SCHEMA PRODUCTO;
CREATE SCHEMA VENTA;

CREATE TABLE PERSONA
(
IDPER INT PRIMARY KEY,
DNIPER CHAR(8),
NOMPER VARCHAR(50),
APEPER VARCHAR(50),
EMAPER VARCHAR(70),
CELPER CHAR(9),
TIPPER CHAR(1),
ESTPER CHAR(1),
FECNACPER DATE
);

CREATE TABLE CATEGORIA
(
IDCAT INT PRIMARY KEY,
NOMCAT VARCHAR(50)
);

CREATE TABLE VENTA
(
IDVENT INT PRIMARY KEY,
FECVEN DATETIME,
IDVEND CHAR(50),
IDCLI CHAR(50),
TIPPAGVEN CHAR(70),
ESTVEN CHAR(9),
);




